name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: make clean
      working-directory: ex29
    - name: make
      run: make
      working-directory: ex29
