name: C/C++ CI

on: [push]

jobs:
  test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ex29
      run: make -f ./ex29/Makefile tests
    - name: ex29 check
      run: make -f ./ex29/Makefile check
